# Generated by Django 3.1.2 on 2020-10-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_auto_20201012_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='tanggal_selesai',
            field=models.DateField(),
        ),
    ]
