# Generated by Django 3.1.2 on 2020-10-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0006_remove_dosen_username'),
        ('mahasiswa', '0004_auto_20201012_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='nama_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membimbing', to='dosen.dosen'),
        ),
    ]
