# Generated by Django 3.1.2 on 2020-10-15 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mahasiswa', '0005_auto_20201014_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkl',
            name='nama_dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='membimbing', to=settings.AUTH_USER_MODEL),
        ),
    ]
