# Generated by Django 2.2 on 2020-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='penulis',
        ),
        migrations.AddField(
            model_name='task',
            name='judul',
            field=models.CharField(default='', max_length=200),
        ),
    ]
