# Generated by Django 2.2 on 2020-08-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200827_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='judul',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='penulis',
            field=models.CharField(default='', max_length=200),
        ),
    ]
