# Generated by Django 2.2 on 2020-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200827_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='penulis',
            field=models.TextField(default=''),
        ),
    ]
