# Generated by Django 2.2 on 2020-09-14 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0002_auto_20200914_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='tgl_kegiatan',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
