# Generated by Django 2.2 on 2020-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catatan', '0003_auto_20200914_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catatan',
            name='ket',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='upload_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
